/**
 * PR body generation utilities
 */

import type { RepositoryDispatchPayload } from '../types.js';

/**
 * Creates a PR body with file list and metadata
 */
export function createPRBody(payload: RepositoryDispatchPayload, filePaths: string[]): string {
  const { figma_file, generated_at } = payload.client_payload;
  const date = new Date(generated_at).toLocaleString('en-US', {
    dateStyle: 'long',
    timeStyle: 'short',
  });

  const fileList = filePaths.map((path) => `- \`${path}\``).join('\n');

  return `## Figma Variables Update

Updated from **${figma_file}** on ${date}

### Files updated
${fileList}

---
*Auto-generated by [Figma VEX](https://github.com/andyhite/figma-vex)*`;
}
